### PR TITLE
Fix NullPointerExcpetion for Updater when the players join

### PR DESCRIPTION
**Pull request by whiler-sesame**
## Proposed changes

Fixed NPE on join related to updater. cacda4930dc1a2daac29f28df49af31c24e5c5cd for players.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the CONTRIBUTING.md
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

No CONTRIBUTING.md to read, no test framework, documentation not required

### CODE REVIEW

**Comment by TheMeinerLP** [comment]
Thanks for the PR, the fix is already implemented in the current Main Branch aka Snapshot 1.2.1. If you or your team have problems, please update to 1.2.1

**Comment by whiler-sesame** [comment]
@TheMeinerLP, can you please, provide a branch name, link to the source code or commit ref with this fix implemented? I can't find any.

**Comment by TheMeinerLP** [comment]
Oh i see. You point at your Join, but my fixes only console
Sorry for that

**Review by TheMeinerLP — APPROVED** [review]

**Comment by TheMeinerLP** [comment]
Small feedback, please put more description into the PR next time. For ex: Add additional null check for hangar updater if the player joins.

Also, please check this list:
image

**Comment by whiler-sesame** [comment]
Sure, but CONTRIBUTING.md is pretty non-trivial to find. Please, consider adding href links to it. Thanks!

**Comment by TheMeinerLP** [comment]
https://github.com/OneLiteFeatherNET/.github/blob/main/CONTRIBUTING.md
Here we go. Github don't cross-link it

**Pull request merged**
